/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIdRouteImport } from './routes/vendor.$id'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicTranslateRouteImport } from './routes/api/public/translate'
import { Route as ApiPublicConciergeRouteImport } from './routes/api/public/concierge'
import { Route as ApiPublicHooksForecastDemandRouteImport } from './routes/api/public/hooks/forecast-demand'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIdRoute = VendorIdRouteImport.update({
  id: '/vendor/$id',
  path: '/vendor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTranslateRoute = ApiPublicTranslateRouteImport.update({
  id: '/api/public/translate',
  path: '/api/public/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConciergeRoute = ApiPublicConciergeRouteImport.update({
  id: '/api/public/concierge',
  path: '/api/public/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksForecastDemandRoute =
  ApiPublicHooksForecastDemandRouteImport.update({
    id: '/api/public/hooks/forecast-demand',
    path: '/api/public/hooks/forecast-demand',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendors': typeof VendorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/track/$code': typeof TrackCodeRoute
  '/vendor/$id': typeof VendorIdRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/hooks/forecast-demand': typeof ApiPublicHooksForecastDemandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendors': typeof VendorsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/track/$code': typeof TrackCodeRoute
  '/vendor/$id': typeof VendorIdRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/hooks/forecast-demand': typeof ApiPublicHooksForecastDemandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendors': typeof VendorsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/track/$code': typeof TrackCodeRoute
  '/vendor/$id': typeof VendorIdRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/hooks/forecast-demand': typeof ApiPublicHooksForecastDemandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/discover'
    | '/sitemap.xml'
    | '/vendors'
    | '/dashboard'
    | '/favorites'
    | '/orders'
    | '/referrals'
    | '/track/$code'
    | '/vendor/$id'
    | '/api/public/concierge'
    | '/api/public/translate'
    | '/api/public/hooks/forecast-demand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/discover'
    | '/sitemap.xml'
    | '/vendors'
    | '/dashboard'
    | '/favorites'
    | '/orders'
    | '/referrals'
    | '/track/$code'
    | '/vendor/$id'
    | '/api/public/concierge'
    | '/api/public/translate'
    | '/api/public/hooks/forecast-demand'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/discover'
    | '/sitemap.xml'
    | '/vendors'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/orders'
    | '/_authenticated/referrals'
    | '/track/$code'
    | '/vendor/$id'
    | '/api/public/concierge'
    | '/api/public/translate'
    | '/api/public/hooks/forecast-demand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DiscoverRoute: typeof DiscoverRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorsRoute: typeof VendorsRoute
  TrackCodeRoute: typeof TrackCodeRoute
  VendorIdRoute: typeof VendorIdRoute
  ApiPublicConciergeRoute: typeof ApiPublicConciergeRoute
  ApiPublicTranslateRoute: typeof ApiPublicTranslateRoute
  ApiPublicHooksForecastDemandRoute: typeof ApiPublicHooksForecastDemandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$id': {
      id: '/vendor/$id'
      path: '/vendor/$id'
      fullPath: '/vendor/$id'
      preLoaderRoute: typeof VendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/translate': {
      id: '/api/public/translate'
      path: '/api/public/translate'
      fullPath: '/api/public/translate'
      preLoaderRoute: typeof ApiPublicTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/concierge': {
      id: '/api/public/concierge'
      path: '/api/public/concierge'
      fullPath: '/api/public/concierge'
      preLoaderRoute: typeof ApiPublicConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/forecast-demand': {
      id: '/api/public/hooks/forecast-demand'
      path: '/api/public/hooks/forecast-demand'
      fullPath: '/api/public/hooks/forecast-demand'
      preLoaderRoute: typeof ApiPublicHooksForecastDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DiscoverRoute: DiscoverRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorsRoute: VendorsRoute,
  TrackCodeRoute: TrackCodeRoute,
  VendorIdRoute: VendorIdRoute,
  ApiPublicConciergeRoute: ApiPublicConciergeRoute,
  ApiPublicTranslateRoute: ApiPublicTranslateRoute,
  ApiPublicHooksForecastDemandRoute: ApiPublicHooksForecastDemandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
